management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: 'always'
    password: ${HEROKU_VACINA_PASS}
    url: jdbc:mysql://us-cdbr-east-03.cleardb.com:3306/heroku_dcddf2366ea4f96?reconnect=true
    username: b4382ad81a1950
  jpa:
    hibernate:
      ddl-auto: 'none  '
