server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: true        
    show-sql: true
    
  devtools:
   livereload:
    enabled: true
       
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true   
    health:
      enabled: true